export const dummydata = [
    {
      id: 1,
      first_name: "Carlos",
      last_name: "Santos",
      address: "123 london,uk",
      postcode: "se10 9fy",
      email_address: "santos.Carlos@gmail.com",
      pet_name: ["Luke", "Juno", "Lupin"],
      pet_age: [1, 3, 0],
      breed: ["shihtzu", "Huskey", "Golden Retriver"],
    },
    {
      id: 2,
      first_name: "Carlos",
      last_name: "Santos",
      address: "123 london,uk",
      postcode: "se10 9fy",
      email_address: "santos.Carlos@gmail.com",
      pet_name: ["Luke", "Juno", "Lupin"],
      pet_age: [1, 3, 0],
      breed: ["shihtzu", "Huskey", "Golden Retriver"],
    },
    {
      id: 3,
      first_name: "Carlos",
      last_name: "Santos",
      address: "123 london,uk",
      postcode: "se10 9fy",
      email_address: "santos.Carlos@gmail.com",
      pet_name: ["Luke", "Juno", "Lupin"],
      pet_age: [1, 3, 0],
      breed: ["shihtzu", "Huskey", "Golden Retriver"],
    },
  ];